trigger: none

variables:
- group: SecretRotation

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  displayName: Rotate App Registration Secrets
  inputs:
    targetType: inline
    script: |
      # ===================================================================
      # CONFIGURATION (FROM VARIABLE GROUP)
      # ===================================================================
      $TenantId           = "$(TenantId)"
      $ClientId           = "$(ClientId)"
      $ClientSecret       = "$(ClientSecret)"
      $KeyVaultName       = "$(KeyVaultName)"
      $SecretDisplayName  = "Auto_renewed"
      $SecretLifeYears    = [int]"$(SecretLifeYears)"

      # Convert comma-separated list into array
      $AppObjectIds = "$(AppObjectIds)".Split(",") | ForEach-Object { $_.Trim() }

      # ===================================================================
      # FUNCTIONS (UNCHANGED)
      # ===================================================================

      function Get-GraphToken {
          $body = @{
              grant_type    = "client_credentials"
              client_id     = $ClientId
              client_secret = $ClientSecret
              scope         = "https://graph.microsoft.com/.default"
          }
          (Invoke-RestMethod -Method Post `
              -Uri "https://login.microsoftonline.com/$TenantId/oauth2/v2.0/token" `
              -Body $body).access_token
      }

      function Get-KeyVaultToken {
          $body = @{
              grant_type    = "client_credentials"
              client_id     = $ClientId
              client_secret = $ClientSecret
              resource      = "https://vault.azure.net"
          }
          (Invoke-RestMethod -Method Post `
              -Uri "https://login.microsoftonline.com/$TenantId/oauth2/token" `
              -Body $body).access_token
      }

      function Get-AppDetails {
          param ($AccessToken, $Identifier)

          try {
              return Invoke-RestMethod `
                  -Method Get `
                  -Uri "https://graph.microsoft.com/v1.0/applications/$Identifier" `
                  -Headers @{ Authorization = "Bearer $AccessToken" }
          } catch {
              Write-Host "Primary lookup failed. Trying appId lookup..."
          }

          $resp = Invoke-RestMethod `
              -Method Get `
              -Uri "https://graph.microsoft.com/v1.0/applications?`$filter=appId eq '$Identifier'" `
              -Headers @{ Authorization = "Bearer $AccessToken" }

          if ($resp.value.Count -gt 0) { return $resp.value[0] }
          return $null
      }

       function Remove-AppSecret {
        param (
            [string]$AccessToken,
            [string]$AppObjectId,
            [string]$SecretId
        )

        $payload  = @{ keyId = $SecretId } | ConvertTo-Json -Depth 10
        $endpoint = "https://graph.microsoft.com/v1.0/applications/$AppObjectId/removePassword"

        $maxRetries = 5

        for ($attempt = 1; $attempt -le $maxRetries; $attempt++) {
            try {
                Invoke-RestMethod `
                    -Method Post `
                    -Uri $endpoint `
                    -Headers @{
                        Authorization = "Bearer $AccessToken"
                        Accept        = "application/json"
                    } `
                    -Body $payload `
                    -ContentType "application/json" `
                    -ErrorAction Stop

                Write-Host "Deleted secret $SecretId for app $AppObjectId"
                return $true
            }
            catch {
                # try to extract status code and response body for diagnostics
                $status = $null
                $body   = $null
                try {
                    if ($_.Exception.Response -ne $null) {
                        $status = $_.Exception.Response.StatusCode.Value__ 2>$null
                        $stream = $_.Exception.Response.GetResponseStream()
                        if ($stream -ne $null) {
                            $sr = New-Object System.IO.StreamReader($stream)
                            $body = $sr.ReadToEnd()
                        }
                    }
                } catch { }

                # If transient (409 or 5xx), retry with backoff
                if ($status -eq 409 -or ($status -ge 500 -and $status -lt 600)) {
                    $delay = [math]::Pow(2, [math]::Min($attempt,4))
                    Write-Warning "Transient error deleting secret $SecretId (HTTP $status). Attempt $attempt/$maxRetries. Retrying in $delay s. Response body: $body"
                    Start-Sleep -Seconds $delay
                    continue
                }

                # Non-retryable: log and continue (do not throw)
                Write-Warning "Failed to delete secret $SecretId (HTTP $status). Response body: $body"
                return $false
            }
        }

        Write-Warning "Failed to delete secret $SecretId after $maxRetries attempts. Continuing."
        return $false
      }


      function New-AppSecret {
          param ($AccessToken, $AppObjectId)

          $payload = @{
              passwordCredential = @{
                  displayName   = $SecretDisplayName
                  startDateTime = (Get-Date).ToString("o")
                  endDateTime   = (Get-Date).AddYears($SecretLifeYears).ToString("o")
              }
          } | ConvertTo-Json

          $maxRetries = 5
          $retryDelay = 5

          for ($i = 1; $i -le $maxRetries; $i++) {
              try {
                  $resp = Invoke-RestMethod `
                      -Method Post `
                      -Uri "https://graph.microsoft.com/v1.0/applications/$AppObjectId/addPassword" `
                      -Headers @{ Authorization = "Bearer $AccessToken" } `
                      -Body $payload `
                      -ContentType "application/json" `
                      -ErrorAction Stop

                  return $resp.secretText
              }
              catch {
                if ($_.Exception.Response -and $_.Exception.Response.StatusCode.Value__ -eq 409) {
                    Write-Warning "409 Conflict creating secret (attempt $i/$maxRetries). Retrying in $retryDelay seconds..."
                    Start-Sleep -Seconds $retryDelay
                    continue
                }

                Write-Warning "Non-retryable error creating secret. Skipping this app."
                return $null
        }

          }

          Write-Error "Secret creation failed after retries."
          return $null
      }

      function Store-SecretInKeyVault {
          param ($SecretName, $SecretValue)

          $kvToken = Get-KeyVaultToken
          $kvUri = "https://{0}.vault.azure.net/secrets/{1}?api-version=7.3" -f `
                    $KeyVaultName, $SecretName

          $payload = @{ value = $SecretValue } | ConvertTo-Json

          Invoke-RestMethod `
              -Method Put `
              -Uri $kvUri `
              -Headers @{
                  Authorization = "Bearer $kvToken"
                  Accept        = "application/json"
              } `
              -Body $payload `
              -ContentType "application/json"
      }

      # ===================================================================
      # MAIN (UNCHANGED)
      # ===================================================================
      Write-Host "Starting secret rotation"

      $graphToken = Get-GraphToken

      foreach ($id in $AppObjectIds) {

          Write-Host "-------------------------------------"
          Write-Host "Processing: $id"

          $app = Get-AppDetails -AccessToken $graphToken -Identifier $id
          if (-not $app) {
              Write-Warning "App not found. Skipping."
              continue
          }

          Write-Host "App Name: $($app.displayName)"
          $appObjectId = $app.id

          Write-Host "Creating new secret..."
          $newSecret = New-AppSecret -AccessToken $graphToken -AppObjectId $appObjectId

          if (-not $newSecret) {
            Write-Warning "Secret creation failed for $($app.displayName). Skipping this app and continuing."
            continue
            }
            $newclientId = if ($app.appId) { $app.appId } else { $app.id }

            $secretName = "appsecret-$newclientId-current"
            Write-Host "Storing Key Vault secret as: $secretName"
            
          Store-SecretInKeyVault -SecretName $secretName -SecretValue $newSecret

          if ($app.passwordCredentials -and $app.passwordCredentials.Count -gt 0) {
              Write-Host "Deleting old secrets..."
              start-sleep -seconds 15
              foreach ($secret in $app.passwordCredentials) {
                  Remove-AppSecret -AccessToken $graphToken `
                                   -AppObjectId $appObjectId `
                                   -SecretId $secret.keyId
                  Start-Sleep -Seconds 2
              }
          }

          Write-Host "Rotation complete for $($app.displayName)"
      }

      Write-Host "Script execution completed."
